//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WJ_Building
    {
        public System.Guid Id { get; set; }
        public string ShortRemark { get; set; }
        public string ContactTel { get; set; }
        public string Address { get; set; }
        public string BuildName { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> StarsCount { get; set; }
        public string BuildIntro { get; set; }
        public Nullable<System.DateTime> OpeningTime { get; set; }
        public string BuildPrice { get; set; }
        public Nullable<System.Guid> BuildType { get; set; }
        public Nullable<int> Households { get; set; }
        public string BelogEstate { get; set; }
        public Nullable<int> Years { get; set; }
        public string SalesAddress { get; set; }
        public string AreaCovered { get; set; }
        public Nullable<int> BuildingCount { get; set; }
        public string RenovationCondition { get; set; }
        public string GreeningRate { get; set; }
        public bool IsDel { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
