//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WJ_Customer
    {
        public int Id { get; set; }
        public string CusName { get; set; }
        public string CusPwd { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public string RegEmail { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public bool IsDel { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
    }
}
