//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WJ_Investment
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Brief { get; set; }
        public string CoverImg { get; set; }
        public string MinMoney { get; set; }
        public string MaxMoney { get; set; }
        public Nullable<int> Sort { get; set; }
        public string InvContent { get; set; }
        public string Aera { get; set; }
        public string ComName { get; set; }
        public string ComAddress { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public Nullable<bool> IsTop { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> UpdateUser { get; set; }
    }
}
