//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WJ_News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Remark { get; set; }
        public string PubUser { get; set; }
        public int ViewTimes { get; set; }
        public Nullable<System.Guid> NewsType { get; set; }
        public Nullable<bool> IsTop { get; set; }
        public Nullable<int> Sort { get; set; }
        public string CoverImg { get; set; }
        public string NewsContent { get; set; }
        public bool IsDel { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> UpdateUser { get; set; }
    }
}
